### ISSUE TITLE
Allow declaring reviewers from keywords

### ISSUE THREAD

**Issue by operte** [timvink/doing-cli#14]
Imagine if I have a long list of contributors or I don't want to set the same default reviewers all the time but I also don't want to type their emails out when declaring the reviewers.

An idea is to allow the user to define a list of contributors on the doing-cli config file, so a keyword (like the first name of the contributor) and its email address:

```yaml
john: john.doe@email.net
jane: jane.doe@webmail.org
```

So then I could do `doing create pr --reviewers john jane`

What do you think? Does it sound useful?

**Comment by timvink** [comment]
Really good idea!

So something like:

```yaml
# .doing-cli-config.yml
# ... other settings ....
aliases:
    - john: john.doe@email.net
    - jane: jane.doe@webmail.org
```

Would allow you to use the aliases in both reviewers and assignees:

- `doing create pr --reviewers 'john jane'`. it needs a string because `--reviewers` takes a single option. `doing` would expand the string to 'john.doe@email.net jane.doe@webmail.org' before passing it to the az devops cli.
- `doing create issue "an issue" -a john` 

It would have to work with `default_reviewers` as well.

Thoughts? And, do you want to work on the PR or shall I pick it up? :)
